### ISSUE TITLE
make getAnatFilename error message more informative

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_SPM#196]
## Describe your problem in detail

My anat file is in the "session-003" but I forgot to change the default "opt.anatReference.session" to "3".

If there is only one anat `T1w` file but not in the default session folder (first session) or the one asked the error message is very unhelpful.

## Describe what outcome you expected 

The error message to tell me where the T1w files are.

### Error message

```
Index exceeds matrix dimensions.

Error in getAnatFilename (line 42)
  anat = anat{1};

Error in setBatchSelectAnat (line 31)
  [anatImage, anatDataDir] = getAnatFilename(BIDS, subID, opt);

Error in bidsSpatialPrepro (line 62)
      matlabbatch = setBatchSelectAnat(matlabbatch, BIDS, opt, subID);

Error in preprocessRetinotopy (line 20)
bidsSpatialPrepro(opt)
```

**Comment by Remi-Gau** [comment]
Alternatively, we could let the pipeline figure out where the anat file is when the user does not say anything.

**Comment by marcobarilari** [comment]
Yes! related to this, you have an error also if you set that your anat is in ses-002 and you have only the ses-002 folder in your dataset.

I guess that the ses nb you set is used as an index to locate the folder among the others. It should instead use it as the folder name.

Moreover, if used as the folder name to locate it, we could use a label that corresponds to the dataset type (e.g. localizer) instead of the nb of session in time

**Comment by Remi-Gau** [comment]
yeah that's another issue. 

Actually there is literally a TODO from past me in that function:

```
% TODO allow for the session to be referenced by a string e.g ses-retest
```

Seems my past self is not a complete idiot / dick.

**Comment by Remi-Gau** [comment]
@marcobarilari 

I am closing this. As it was fixed by the PR on my side. 

If you still have problems on your side: feel free to reopen it.

**Comment by Remi-Gau** [comment]
@all-contributors please add @Remi-Gau  for bug
